// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzn82Ab3-RQTFipQVKlzE8RlutgDCaqbI',
    appId: '1:332165266496:web:d182062e0bbdd04af1f3a5',
    messagingSenderId: '332165266496',
    projectId: 'guconnect-aed4f',
    authDomain: 'guconnect-aed4f.firebaseapp.com',
    storageBucket: 'guconnect-aed4f.appspot.com',
    measurementId: 'G-3DZ279J9D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRgPA2P7B_bFNUKcBsIp_aTodNP26Dh-0',
    appId: '1:332165266496:android:787f108300ff390bf1f3a5',
    messagingSenderId: '332165266496',
    projectId: 'guconnect-aed4f',
    storageBucket: 'guconnect-aed4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbAWnPtLoWc3LyZ-UJjZVEMmhSuPROFkI',
    appId: '1:332165266496:ios:e169ce7f92e68378f1f3a5',
    messagingSenderId: '332165266496',
    projectId: 'guconnect-aed4f',
    storageBucket: 'guconnect-aed4f.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbAWnPtLoWc3LyZ-UJjZVEMmhSuPROFkI',
    appId: '1:332165266496:ios:2f1c807e2e49eef6f1f3a5',
    messagingSenderId: '332165266496',
    projectId: 'guconnect-aed4f',
    storageBucket: 'guconnect-aed4f.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
